### ISSUE TITLE
Handle aspect ratio better 

### ISSUE THREAD

**Issue by cubimon** [cubimon/windowed-fullscreen-video#1]
If the window's aspect ratio doesn't match the aspect ratio of the video, black bars should be displayed or the video should be cropped.

Configure in config page like on a TV or via hotkey/popup?

**Comment by Cimbali** [comment]
All that would be needed to implement “black bars” is to add a `background-color: black;` to the video element when it is transformed.

As a temporary work-around, you can add a userstyle that does this:

```css
body > div > video {
    background-color: black;
}
```
